//! Opcode dispatch table generated by the [`opcodes!`] macro.
//!
//! The table maps all 256 possible opcode bytes to their handler,
//! addressing mode, and base cycle count. Unmapped opcodes are
//! detected by `lookup()` before dispatch.

use super::addr::AddrMode;
use super::handlers::{self, OpHandler};
use super::step::StepErr;

/// A single entry in the opcode dispatch table.
#[derive(Clone, Copy)]
pub(super) struct OpEntry {
    /// Instruction handler function.
    pub(super) handler: OpHandler,
    /// Addressing mode to resolve before calling the handler.
    pub(super) mode: AddrMode,
    /// Base cycle count (before page-cross or branch-taken penalties).
    pub(super) base_cycles: u8,
    /// Whether this is a legal (official) opcode.
    legal: bool,
}

/// Looks up an opcode in the dispatch table.
///
/// Returns `Err(StepErr::IllegalOpcode)` for unmapped opcodes.
pub(super) fn lookup(opcode: u8) -> Result<OpEntry, StepErr> {
    let entry = OPCODE_TABLE
        .get(usize::from(opcode))
        .copied()
        .ok_or(StepErr::IllegalOpcode(opcode))?;
    if entry.legal {
        Ok(entry)
    } else {
        Err(StepErr::IllegalOpcode(opcode))
    }
}

/// Generates the 256-entry opcode dispatch table at compile time.
///
/// Each line maps an opcode byte to a handler function, addressing
/// mode, and base cycle count.
macro_rules! opcodes {
    ( $( $opcode:literal => $handler:ident, $mode:ident, $cy:literal );* $(;)? ) => {
        #[allow(clippy::indexing_slicing)]
        const fn build_table() -> [OpEntry; 256] {
            let default = OpEntry {
                handler: handlers::illegal as OpHandler,
                mode: AddrMode::Implicit,
                base_cycles: 0,
                legal: false,
            };
            let mut table = [default; 256];
            $(
                table[$opcode] = OpEntry {
                    handler: handlers::$handler as OpHandler,
                    mode: AddrMode::$mode,
                    base_cycles: $cy,
                    legal: true,
                };
            )*
            table
        }
    };
}

// ── Full 6502 opcode table (151 official opcodes) ────────────────

opcodes! {
    // ── ADC ──────────────────────────────────────────────────────
    0x69 => adc, Immediate, 2;
    0x65 => adc, ZeroPage,  3;
    0x75 => adc, ZeroPageX, 4;
    0x6D => adc, Absolute,  4;
    0x7D => adc, AbsoluteX, 4;
    0x79 => adc, AbsoluteY, 4;
    0x61 => adc, IndirectX, 6;
    0x71 => adc, IndirectY, 5;

    // ── SBC ──────────────────────────────────────────────────────
    0xE9 => sbc, Immediate, 2;
    0xE5 => sbc, ZeroPage,  3;
    0xF5 => sbc, ZeroPageX, 4;
    0xED => sbc, Absolute,  4;
    0xFD => sbc, AbsoluteX, 4;
    0xF9 => sbc, AbsoluteY, 4;
    0xE1 => sbc, IndirectX, 6;
    0xF1 => sbc, IndirectY, 5;

    // ── AND ──────────────────────────────────────────────────────
    0x29 => and, Immediate, 2;
    0x25 => and, ZeroPage,  3;
    0x35 => and, ZeroPageX, 4;
    0x2D => and, Absolute,  4;
    0x3D => and, AbsoluteX, 4;
    0x39 => and, AbsoluteY, 4;
    0x21 => and, IndirectX, 6;
    0x31 => and, IndirectY, 5;

    // ── ORA ──────────────────────────────────────────────────────
    0x09 => ora, Immediate, 2;
    0x05 => ora, ZeroPage,  3;
    0x15 => ora, ZeroPageX, 4;
    0x0D => ora, Absolute,  4;
    0x1D => ora, AbsoluteX, 4;
    0x19 => ora, AbsoluteY, 4;
    0x01 => ora, IndirectX, 6;
    0x11 => ora, IndirectY, 5;

    // ── EOR ──────────────────────────────────────────────────────
    0x49 => eor, Immediate, 2;
    0x45 => eor, ZeroPage,  3;
    0x55 => eor, ZeroPageX, 4;
    0x4D => eor, Absolute,  4;
    0x5D => eor, AbsoluteX, 4;
    0x59 => eor, AbsoluteY, 4;
    0x41 => eor, IndirectX, 6;
    0x51 => eor, IndirectY, 5;

    // ── ASL ──────────────────────────────────────────────────────
    0x0A => asl_acc, Accumulator, 2;
    0x06 => asl_mem, ZeroPage,    5;
    0x16 => asl_mem, ZeroPageX,   6;
    0x0E => asl_mem, Absolute,    6;
    0x1E => asl_mem, AbsoluteX,   7;

    // ── LSR ──────────────────────────────────────────────────────
    0x4A => lsr_acc, Accumulator, 2;
    0x46 => lsr_mem, ZeroPage,    5;
    0x56 => lsr_mem, ZeroPageX,   6;
    0x4E => lsr_mem, Absolute,    6;
    0x5E => lsr_mem, AbsoluteX,   7;

    // ── ROL ──────────────────────────────────────────────────────
    0x2A => rol_acc, Accumulator, 2;
    0x26 => rol_mem, ZeroPage,    5;
    0x36 => rol_mem, ZeroPageX,   6;
    0x2E => rol_mem, Absolute,    6;
    0x3E => rol_mem, AbsoluteX,   7;

    // ── ROR ──────────────────────────────────────────────────────
    0x6A => ror_acc, Accumulator, 2;
    0x66 => ror_mem, ZeroPage,    5;
    0x76 => ror_mem, ZeroPageX,   6;
    0x6E => ror_mem, Absolute,    6;
    0x7E => ror_mem, AbsoluteX,   7;

    // ── CMP ──────────────────────────────────────────────────────
    0xC9 => cmp, Immediate, 2;
    0xC5 => cmp, ZeroPage,  3;
    0xD5 => cmp, ZeroPageX, 4;
    0xCD => cmp, Absolute,  4;
    0xDD => cmp, AbsoluteX, 4;
    0xD9 => cmp, AbsoluteY, 4;
    0xC1 => cmp, IndirectX, 6;
    0xD1 => cmp, IndirectY, 5;

    // ── CPX ──────────────────────────────────────────────────────
    0xE0 => cpx, Immediate, 2;
    0xE4 => cpx, ZeroPage,  3;
    0xEC => cpx, Absolute,  4;

    // ── CPY ──────────────────────────────────────────────────────
    0xC0 => cpy, Immediate, 2;
    0xC4 => cpy, ZeroPage,  3;
    0xCC => cpy, Absolute,  4;

    // ── INC ──────────────────────────────────────────────────────
    0xE6 => inc, ZeroPage,  5;
    0xF6 => inc, ZeroPageX, 6;
    0xEE => inc, Absolute,  6;
    0xFE => inc, AbsoluteX, 7;

    // ── DEC ──────────────────────────────────────────────────────
    0xC6 => dec, ZeroPage,  5;
    0xD6 => dec, ZeroPageX, 6;
    0xCE => dec, Absolute,  6;
    0xDE => dec, AbsoluteX, 7;

    // ── INX / INY / DEX / DEY ────────────────────────────────────
    0xE8 => inx, Implicit, 2;
    0xC8 => iny, Implicit, 2;
    0xCA => dex, Implicit, 2;
    0x88 => dey, Implicit, 2;

    // ── LDA ──────────────────────────────────────────────────────
    0xA9 => lda, Immediate, 2;
    0xA5 => lda, ZeroPage,  3;
    0xB5 => lda, ZeroPageX, 4;
    0xAD => lda, Absolute,  4;
    0xBD => lda, AbsoluteX, 4;
    0xB9 => lda, AbsoluteY, 4;
    0xA1 => lda, IndirectX, 6;
    0xB1 => lda, IndirectY, 5;

    // ── LDX ──────────────────────────────────────────────────────
    0xA2 => ldx, Immediate, 2;
    0xA6 => ldx, ZeroPage,  3;
    0xB6 => ldx, ZeroPageY, 4;
    0xAE => ldx, Absolute,  4;
    0xBE => ldx, AbsoluteY, 4;

    // ── LDY ──────────────────────────────────────────────────────
    0xA0 => ldy, Immediate, 2;
    0xA4 => ldy, ZeroPage,  3;
    0xB4 => ldy, ZeroPageX, 4;
    0xAC => ldy, Absolute,  4;
    0xBC => ldy, AbsoluteX, 4;

    // ── STA ──────────────────────────────────────────────────────
    0x85 => sta, ZeroPage,  3;
    0x95 => sta, ZeroPageX, 4;
    0x8D => sta, Absolute,  4;
    0x9D => sta, AbsoluteX, 5;
    0x99 => sta, AbsoluteY, 5;
    0x81 => sta, IndirectX, 6;
    0x91 => sta, IndirectY, 6;

    // ── STX ──────────────────────────────────────────────────────
    0x86 => stx, ZeroPage,  3;
    0x96 => stx, ZeroPageY, 4;
    0x8E => stx, Absolute,  4;

    // ── STY ──────────────────────────────────────────────────────
    0x84 => sty, ZeroPage,  3;
    0x94 => sty, ZeroPageX, 4;
    0x8C => sty, Absolute,  4;

    // ── Transfers ────────────────────────────────────────────────
    0xAA => tax, Implicit, 2;
    0xA8 => tay, Implicit, 2;
    0x8A => txa, Implicit, 2;
    0x98 => tya, Implicit, 2;
    0xBA => tsx, Implicit, 2;
    0x9A => txs, Implicit, 2;

    // ── Stack ────────────────────────────────────────────────────
    0x48 => pha, Implicit, 3;
    0x08 => php, Implicit, 3;
    0x68 => pla, Implicit, 4;
    0x28 => plp, Implicit, 4;

    // ── Branches ─────────────────────────────────────────────────
    0x90 => bcc, Relative, 2;
    0xB0 => bcs, Relative, 2;
    0xF0 => beq, Relative, 2;
    0xD0 => bne, Relative, 2;
    0x30 => bmi, Relative, 2;
    0x10 => bpl, Relative, 2;
    0x50 => bvc, Relative, 2;
    0x70 => bvs, Relative, 2;

    // ── Jumps / Returns ──────────────────────────────────────────
    0x4C => jmp, Absolute, 3;
    0x6C => jmp, Indirect, 5;
    0x20 => jsr, Absolute, 6;
    0x60 => rts, Implicit, 6;
    0x40 => rti, Implicit, 6;

    // ── Flags ────────────────────────────────────────────────────
    0x18 => clc, Implicit, 2;
    0x38 => sec, Implicit, 2;
    0x58 => cli, Implicit, 2;
    0x78 => sei, Implicit, 2;
    0xB8 => clv, Implicit, 2;
    0xD8 => cld, Implicit, 2;
    0xF8 => sed, Implicit, 2;

    // ── BIT ──────────────────────────────────────────────────────
    0x24 => bit, ZeroPage, 3;
    0x2C => bit, Absolute, 4;

    // ── NOP ──────────────────────────────────────────────────────
    0xEA => nop, Implicit, 2;

    // ── BRK ──────────────────────────────────────────────────────
    0x00 => brk, Implicit, 7;
}

/// Dispatch table for all 256 opcodes, built at compile time.
const OPCODE_TABLE: [OpEntry; 256] = build_table();
